##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.7.0-B52] date: [Fri Oct 17 16:54:42 HKT 2025] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = Assignment2


######################################
# building variables
######################################
# debug option
#-g0	no debug information
#-g1	minimal debug information
#-g		default debug information
#-g3	maximal debug information
DEBUG = -g3

# optimization
# -O0 		no optimization
# -O1 		
# -O2
# -O3
# -Os 		optimize for size
# -Ofast 	optimize for speed
# -Og 		optimize for debugging
OPT = -O0

# silent mode
VERBOSE = 0

# C standard
CSTD = -std=gnu11

# C++ standard
CPPSTD = -std=gnu++20

#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES = \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/stm32g4xx_it.c \
Core/Src/stm32g4xx_hal_msp.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
Core/Src/usart.c \
Core/Src/fdcan.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_fdcan.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_rcc_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_flash_ramfunc.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_gpio.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_exti.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_dma_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_pwr_ex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_cortex.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart.c \
Drivers/STM32G4xx_HAL_Driver/Src/stm32g4xx_hal_uart_ex.c \
Core/Src/system_stm32g4xx.c \
Core/Src/dma.c


CPP_SOURCES  = \
$(wildcard Core/Src/*.cpp) \
$(wildcard Core/Modules/*.cpp) 

# ASM sources
ASM_SOURCES =  \
startup_stm32g431xx.s


# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32G431xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-ICore/Modules \
-IDrivers/STM32G4xx_HAL_Driver/Inc \
-IDrivers/STM32G4xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32G4xx/Include \
-IDrivers/CMSIS/Include \
-IMiddlewares/ST/ARM/DSP/Inc

#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc							# c compiler
CPPC = $(GCC_PATH)/$(PREFIX)g++							# CPP compiler
AS = $(GCC_PATH)/$(PREFIX)g++ -x assembler-with-cpp		# assembler
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc										# c compiler
CPPC = $(PREFIX)g++										# CPP compiler
AS = $(PREFIX)g++ -x assembler-with-cpp					# assembler
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S


#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)


# compile flags
COMPILERFLAGS = $(MCU)								# MCU

COMPILERFLAGS += -fdata-sections					# Place each data item into its own section
COMPILERFLAGS += -ffunction-sections				# Place each function into its own section
COMPILERFLAGS += -fstack-usage						# Generate stack usage information

COMPILERFLAGS += -specs=nano.specs					# Use newlib-nano

COMPILERFLAGS += $(OPT)								# Optimization

COMPILERFLAGS += -pipe								# Use pipes rather than temporary files

COMPILERFLAGS += -Wfatal-errors						# Stop after the first error

COMPILERFLAGS += -Wall 								# Enable all warnings
COMPILERFLAGS += -Wextra							# Enable extra warnings
COMPILERFLAGS += -Wpedantic							# Warn about anything that does not conform to the standard
COMPILERFLAGS += -Wshadow							# Warn about shadowed variables
COMPILERFLAGS += -Wdouble-promotion					# Warn about implicit conversion from float to double
COMPILERFLAGS += -Wlogical-op						# Warn about suspicious uses of logical operators
COMPILERFLAGS += -Wpointer-arith					# Warn about pointer arithmetic
COMPILERFLAGS += -Wmissing-field-initializers		# Warn about missing field initializers

COMPILERFLAGS += -Wno-unused-parameter				# Disable warning about unused parameters
COMPILERFLAGS += -Wno-unused-const-variable			# Disable warning about unused const variables

COMPILERFLAGS += -fdiagnostics-color=auto			# Enable colored diagnostics

# Debug
ifneq ($(DEBUG), -g0)
COMPILERFLAGS += $(DEBUG) -gdwarf-4
endif

# Generate dependency information
COMPILERFLAGS += -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@"

ASFLAGS = $(AS_DEFS) $(AS_INCLUDES) $(COMPILERFLAGS)

CFLAGS = $(C_DEFS) $(C_INCLUDES) $(CSTD) $(COMPILERFLAGS)

CPPFLAGS = $(C_DEFS) $(C_INCLUDES) $(CPPSTD) $(COMPILERFLAGS)
CPPFLAGS += -fno-exceptions							# Disable exceptions
CPPFLAGS += -fno-rtti								# Disable rtti (eg: typeid, dynamic_cast)
CPPFLAGS += -fno-threadsafe-statics					# Disable thread safe statics


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32G431XX_FLASH.ld
LDSCRIPT = STM32G431XX_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections 


# Hide details (silent mode)
ifeq ($(VERBOSE),1)
Q:=
else
Q:=@
endif

BUILD_SUCCESS = @echo -e "\033[2K\033[92mBuild Success!\033[m\n"

ifndef ECHO 
HIT_TOTAL != ${MAKE} ${MAKECMDGOALS} --dry-run ECHO="HIT_MARK" | grep -c "HIT_MARK"
HIT_COUNT = $(eval HIT_N != expr ${HIT_N} + 1)${HIT_N}
ECHO = @echo -e "\033[2K\033[96;49;4m[`expr ${HIT_COUNT} '*' 100 / ${HIT_TOTAL}`%]Building:\033[m$(notdir $<)\r\c"
endif
# $(info $(HIT_TOTAL) $(HIT_COUNT) $(ECHO))

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin
	$(ECHO) $@
	$(BUILD_SUCCESS)
	$(SZ) $(BUILD_DIR)/$(TARGET).elf

#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(C_SOURCES:.c=.o))
vpath %.c $(sort $(dir $(C_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(CPP_SOURCES:.cpp=.o))
vpath %.cpp $(sort $(dir $(CPP_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(CPP_COMPILED))
vpath %.s $(sort $(dir $(CPP_COMPILED)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(ASM_SOURCES:.s=.o))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
# Pre-compiled object files
PRECOMPILED_OBJECTS = \
Core/Modules/Evaluation.o
OBJECTS += $(addprefix $(BUILD_DIR)/,$(PRECOMPILED_OBJECTS))

# Print info
$(info Target: $(TARGET))
$(info Core:   $(CORE_DIR))
$(info )
$(info C sources: $(C_SOURCES))
$(info CPP sources: $(CPP_SOURCES))
$(info ASM sources: $(ASM_SOURCES))
$(info )

# Build .c files
$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(ECHO) $@
	@mkdir -p $(dir $@)
	$(Q)$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(<:.c=.lst) $< -o $@

# Build .cpp files
$(BUILD_DIR)/%.o: %.cpp Makefile | $(BUILD_DIR) 
	$(ECHO) $@
	@mkdir -p $(dir $@)
	$(Q)$(CPPC) -c $(CPPFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(<:.cpp=.lst) $< -o $@

# Build .s files
$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(ECHO) $@
	@mkdir -p $(dir $@)
	$(Q)$(AS) -c $(ASFLAGS) $< -o $@

$(BUILD_DIR)/%.o: %.o Makefile | $(BUILD_DIR)
	$(ECHO) $@
	@mkdir -p $(dir $@)
	@cp $< $@

# Build .elf file
$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(ECHO) $@
	$(Q)$(CC) $(OBJECTS) $(LDFLAGS) -o $@

# Build .hex file
$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(ECHO) $@
	$(Q)$(HEX) $< $@
	
# Build .bin file
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(ECHO) $@
	$(Q)$(BIN) $< $@	

# mkdir
$(BUILD_DIR):
	$(Q)mkdir -p $@


# Clean up
clean:
	@echo -e "\033[2K\033[96mCleaning up...\033[m"
	@-rm -fR $(BUILD_DIR)

# Rebuild
rebuild: 
	$(Q)$(MAKE) -s clean
	$(Q)$(MAKE) -s all

# Show size
size: $(BUILD_DIR)/$(TARGET).elf
	$(Q)$(SZ) $<


# the following filenames are not allowed
.PHONY: all clean list size rebuild


#######################################
# dependencies
#######################################
-include $(OBJECTS:%.o=%.d)
